[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 200

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.filemanager]
animation = "fromTop"
command = "kitty --class kitty-dropterm ranger"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 200
